### ISSUE TITLE
Empty pages for transcations

### ISSUE THREAD

**Issue by MauseHund** [team-exor/eiquidus#12]
![pagetranserr1](https://user-images.githubusercontent.com/70485681/159487506-97bc279b-5955-4d28-aa31-4eb029b641b5.png)
Hi, we face a lot of empty transaction-pages on our Scrypt 2.13 Coins eIquidus Explorer v1.99.0 at the very start of the pages (pages 42493 to 4xxxx). We found out about this, as we wanted to view the very first transation.

Not sure what does cause this problem. Can you help?

**Comment by joeuhren** [comment]
Which coin(s) are you seeing this behavior with?

**Comment by MauseHund** [comment]
Solved. Thanks to @joeuhren for the fast response on this!
Usage:

npm run reindex-txcount
