### ISSUE TITLE
install question

### ISSUE THREAD

**Issue by wuhonchi** [team-exor/eiquidus#16]
hi all ,

i do know node and mongodb and did setup geth as well , but i dont know whats the use of coin daemon , and how to setup , is there any more explanation or tutorial ?

thanks

**Comment by joeuhren** [comment]
If you read the very first sentence in the README, you will notice that this explorer is designed to work for altcoins cloned from bitcoin. It does not work for Ethereum since that coin does not utilize the [Bitcoin RPC API protocol](https://developer.bitcoin.org/reference/rpc/index.html).
