### ISSUE TITLE
Unable to start explorer NPM server

### ISSUE THREAD

**Issue by enkrypt3d** [team-exor/eiquidus#19]
Getting this over and over again after trying npm start on GCP: what am I missing? nothing else is using port 80. where is the bind address set??

Cluster restarting...
Initializing database.. Please wait...
Database initialization complete
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: bind EACCES :::80
    at listenOnPrimaryHandle (node:net:1500:18)
    at rr (node:internal/cluster/child:159:12)
    at Worker.<anonymous> (node:internal/cluster/child:109:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:525:35)
    at emit (node:internal/child_process:939:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
Emitted 'error' event on Server instance at:
    at listenOnPrimaryHandle (node:net:1501:21)
    at rr (node:internal/cluster/child:159:12)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (node:internal/process/task_queues:84:21) {
  errno: -13,
  code: 'EACCES',
  syscall: 'bind',
  address: '::',
  port: 80

**Comment by joeuhren** [comment]
I assume it works fine when you use another higher port number like the default port 3001?

There are restrictions in place by default on most Linux systems that prevent you from running apps on ports lower than 1024. There are a couple options outlined here: [https://github.com/team-exor/eiquidus#run-express-webserver-on-port-80](https://github.com/team-exor/eiquidus#run-express-webserver-on-port-80). I'm not sure if the setcap option will work on GCP so you may have to go with the reverse proxy method which should work anywhere. If all else fails you can always just run the explorer as the root user which should give it the permissions needed to run on any port.

**Comment by enkrypt3d** [comment]
As soon as I submitted this, I saw the port change sudo setcap
cap_net_bind_service=+ep `readlink -f \`which node\`` which worked! Thank
you so much for your help

**Comment by enkrypt3d** [comment]
I just need to get it working on 443 only but haven't had much luck yet

**Comment by joeuhren** [comment]
> I just need to get it working on 443 only but haven't had much luck yet

Definitely make sure it's working on port 80 normally before trying to install the ssl certificates (sounds like you already got that far). Follow along with the instructions from [https://github.com/team-exor/eiquidus#tlsssl-support](https://github.com/team-exor/eiquidus#tlsssl-support) and if you did everything correctly it should "just work". Don't forget to allow port 443 and/or 80 through any firewalls you may have installed. Also, if you are using a ddos or reverse proxy service like cloudflare, I've found recently that the instructions I have for enabling ssl won't work and you will likely need to utilize whatever ssl certificates from cloudflare instead for example.

Hope that helps!

**Comment by enkrypt3d** [comment]
Working on moving it to SSL but I had a question - I have new master nodes up but what ports are required for the explorer to reach the master nodes? I am able to send and receive funds so that is working. Just trying to get the explorer to see the new master nodes. 

![image](https://user-images.githubusercontent.com/93238214/193653324-825dd93e-34cc-4c8a-9bec-d75d1ff537d5.png)

**Comment by joeuhren** [comment]
If you want to make the explorer wallet more connectable to other nodes on the network, you can open whatever p2p port your coin uses in your firewall. The port is different for every coin and you can override it via config file as well so I cannot tell you which port that is!

That being said, the online vs unreachable masternodes panel image you are showing shouldn't have much to do with opening up ports for your wallet. It is simply running your `masternode count` cmd and showing the difference between the `total` and `enabled` masternodes:
![image](https://user-images.githubusercontent.com/46763106/193682206-055b8a67-0e98-4a33-9cb8-60ef2af5c6fd.png)
![image](https://user-images.githubusercontent.com/46763106/193682315-6afc7fb2-a5dd-40fe-9be4-67200a63e9ee.png)

In your case, you have a total of 4 masternodes, but only 1 of them is showing as enabled. This has little or nothing to do with the explorer and is just retrieving data from your coin network about the status of your masternodes.

**Comment by enkrypt3d** [comment]
The wallet daemon that is running on the explorer is open (40666 / 40555)
as well as the 8 master nodes running on remote servers. the blockchain is
up and functional, just the explorer cannot see them for some reason....

where are the ports defined? and what is required for explorer to find all
the master nodes? thanks for your help!

**Comment by joeuhren** [comment]
Are you 100% sure the explorer wallet is on the correct chain and hasn't forked onto another chain? Maybe try rebooting the server and/or the wallet itself. The explorer doesn't define any ports or do anything special to somehow "connect" to your masternodes, it only connects to the wallet you defined in the explorer config and gets all the data from that wallet. So if somehow the data is not as you expect, you need to figure out what is wrong with your wallet, it has nothing to do with the explorer.

**Comment by joeuhren** [comment]
Closing this ticket due to inactivity and because it seems to be a wallet issue and not an explorer issue.
