### ISSUE TITLE
Coin Supply issue

### ISSUE THREAD

**Issue by LiteRedCoin** [team-exor/eiquidus#26]
Coin Supply keeps 0. 
How I can fix it. It is PoW+PoS coin. 
Blackcoin fork.

**Comment by LiteRedCoin** [comment]
Never mind. Solved.

**Comment by joeuhren** [comment]
In case anyone else happens across this problem in the future, you need to do the following:

1. Review the options for sync.supply in the settings.json and choose the most appropriate option. (restart the explorer if you made a change)
2. Run a block sync with `npm run sync-blocks` which will populate the coin supply value at the very beginning of the sync

If you have already performed the 2 steps and it still isn't working then you most likely have chosen a sync.supply option that is not valid for your blockchain. Go back to step 1 and choose another option and try again.
