### ISSUE TITLE
logo does not appear in the market, address tabs

### ISSUE THREAD

**Issue by luc1anocruz** [team-exor/eiquidus#29]
logo does not appear in the market, address tabs, because the data is loaded differently, example: http://localhost/address/img/page-title-img.png or http://localhost/markets/southxchange/COIN/img/ page-title-img.png

**Comment by luc1anocruz** [comment]
I had to put / in front of the image address

**Comment by joeuhren** [comment]
You should not need to custom edit the code to make images work. There is an option in the settings (shared_pages > page_header > page_title_image) where you can set the name and location of that image. I would recommend that you restore the original value for that setting. Then make sure you put your image in the /public/img directory and it should work fine without modifying the code which will inhibit your ability to receive code updates.
