### ISSUE TITLE
Call to /api/getdifficulty comes up with error

### ISSUE THREAD

**Issue by D3VIL2009** [team-exor/eiquidus#32]
[explorer-out.log](https://github.com/team-exor/eiquidus/files/12488775/explorer-out.log)
attached is my log file for explorer

I get the same error which ever api i call i make from browser, also difficulty and network hash rate do not show values on explorer page and im assuming this could be to do with this error too.

the graphs also are not showing data

edit : 
i also get this error when trying to reindex from CLI -
Error: Unable to connect to explorer API

i was using npm run reindex when this happened

anyone got any ideas how to fix?

thankyou

**Comment by joeuhren** [comment]
The "Unable to connect to explorer API" error means you have a problem connecting to your wallet daemon. All data comes from the coin wallet so if you don't set up that part correctly, the explorer is pretty useless as you have discovered.

The settings for connecting the explorer to your wallet are right near the top of the settings.json file:
![image](https://github.com/team-exor/eiquidus/assets/46763106/de3e8f6f-8854-43b7-b934-75309f84d25b)

Obviously make sure that your wallet is running and double-check the config file for the wallet to ensure you have the correct username and password. A common mistake is using the wallets p2p port. You will need to use the wallet's rpc port.

Make the necessary changes, then restart the explorer. Everything should begin to work a lot better once you have a proper connection to your wallet software ;)

**Comment by D3VIL2009** [comment]
Thats amazing - i put in the wrong password by mistake by only one letter
:( thanks for the reply it works now. i must have checked everything about
50 times.
