### ISSUE TITLE
masternode not showing

### ISSUE THREAD

**Issue by cryptonana** [team-exor/eiquidus#38]
Script launched with pid: 80838
Syncing masternodes.. Please wait..
Masternode sync complete

but masternode not showing in MN page and not show in title

**Comment by joeuhren** [comment]
Only certain versions of dash and pivx masternode formats are currently supported. Basically, the data coming out of your wallets masternode list cmd should be in a similar format to this:
```
[
  {
    "rank": 95,
    "network": "ipv6",
    "txhash": "c53486cf2608099736c0d561448ef64a1b8e4021d5a479a72cfbf582f48c4da2",
    "outidx": 1,
    "status": "ENABLED",
    "addr": "EU2sWukK7KJiTRPCmT8XPu21DxBdidUtdi",
    "version": 70914,
    "lastseen": 1704843885,
    "activetime": 10275702,
    "lastpaid": 1704843550
  },
  {
    "rank": 96,
    "network": "ipv4",
    "txhash": "6141813996f26e65eb3bdc63b375c640c5372731f98ce570a72804b2125ee052",
    "outidx": 1,
    "status": "ENABLED",
    "addr": "EbeqTtZe57uqCYJjSYMtNtV4chXsuuoiEY",
    "version": 70914,
    "lastseen": 1704843815,
    "activetime": 25414145,
    "lastpaid": 1704840449
  },
  {
    "rank": 97,
    "network": "ipv6",
    "txhash": "c78fe21c0131c5146e4c121de62f712d6a775089954dfd8b88a15637b8b14310",
    "outidx": 0,
    "status": "ENABLED",
    "addr": "ESA7vLuttECENnZRLNqL74ryQs2GNNyMRu",
    "version": 70914,
    "lastseen": 1704844153,
    "activetime": 25512823,
    "lastpaid": 1704840986
  }
]
```

Check your wallet first and make sure that it supports a similar format. You may need to look at the optional parameters for the masternode list cmd to output in a different format than the default. The default masternode list cmd that the explorer uses is `listmasternodes`. Assuming your wallet does have support for the same or similar format but isn't the `listmasternodes` cmd, you can change the cmd that is used by the explorer by changing the api_cmds.getmasternodelist setting in the settings.json file:

![image](https://github.com/team-exor/eiquidus/assets/46763106/0faf9153-fb29-4553-8d24-d75b455779c4)

If that still doesn't help, please provide more info about which coin you are trying to sync and what coin(s) it might be a clone of, along with a sample of the masternode list output from the wallet to use for comparison.

**Comment by joeuhren** [comment]
I'm closing this as complete for now since there hasn't been any activity for a number of months. There have been some changes to the explorer to support more masternode formats since this issue was opened so updating to the latest explorer source code might resolve this. Feel free to reopen this issue if you are still experiencing issues getting masternodes to show up.
