### ISSUE TITLE
Sync issue with coin Social Send

### ISSUE THREAD

**Issue by grigzy28** [team-exor/eiquidus#40]
This coin has a current explorer running on the code base of iquidus.  Don't know any of their specifics.  I just downloaded the code in 
the past week, will run an update real quick as well.

I can provide a bootstrap if needed, it's about 2.25gb...  the blocks count is up to 3.2m...

Thanks

edit: https://github.com/SocialSend/SocialSend

edit 2: updated explorer.js file but still same error as the 2nd one
-------------------------------------------------------

Error during initial sync:

'npm run reindex'

```
84165: c287f659ea6268aab3eeb957c1a6529fa2fda732eab71f6ca48f350dedacce9d
84165: 4bd23d3e93efa9b62de37b1a64fed141e82141be068a01ef2dfa4be1cad5d66c
/root/sendexplorer/lib/explorer.js:1088
    module.exports.syncLoop(array.length, function (loop) {
                                                   ^

RangeError: Maximum call stack size exceeded
    at /root/sendexplorer/lib/explorer.js:1088:52
    at Object.next (/root/sendexplorer/lib/explorer.js:846:13)
    at /root/sendexplorer/lib/explorer.js:1097:14
    at Object.next (/root/sendexplorer/lib/explorer.js:846:13)
    at /root/sendexplorer/lib/explorer.js:1097:14
    at Object.next (/root/sendexplorer/lib/explorer.js:846:13)
    at /root/sendexplorer/lib/explorer.js:1097:14
    at Object.next (/root/sendexplorer/lib/explorer.js:846:13)
    at /root/sendexplorer/lib/explorer.js:1097:14
    at Object.next (/root/sendexplorer/lib/explorer.js:846:13)
    at /root/sendexplorer/lib/explorer.js:1097:14
    at Object.next (/root/sendexplorer/lib/explorer.js:846:13)
    at /root/sendexplorer/lib/explorer.js:1097:14
    at Object.next (/root/sendexplorer/lib/explorer.js:846:13)
    at /root/sendexplorer/lib/explorer.js:1097:14
    at Object.next (/root/sendexplorer/lib/explorer.js:846:13)

Node.js v20.5.1
root@shawnvpslenexa241:~/sendexplorer# 
```

And after running `npm run sync-blocks` 

```
root@shawnvpslenexa241:~/sendexplorer# npm run sync-blocks
Script launched with pid: 2358412
Syncing blocks.. Please wait..
/root/sendexplorer/lib/explorer.js:823
        if (done) {
        ^

RangeError: Maximum call stack size exceeded
    at Object.next (/root/sendexplorer/lib/explorer.js:823:9)
    at /root/sendexplorer/lib/explorer.js:1097:14
    at Object.next (/root/sendexplorer/lib/explorer.js:846:13)
    at /root/sendexplorer/lib/explorer.js:1097:14
    at Object.next (/root/sendexplorer/lib/explorer.js:846:13)
    at /root/sendexplorer/lib/explorer.js:1097:14
    at Object.next (/root/sendexplorer/lib/explorer.js:846:13)
    at /root/sendexplorer/lib/explorer.js:1097:14
    at Object.next (/root/sendexplorer/lib/explorer.js:846:13)
    at /root/sendexplorer/lib/explorer.js:1097:14
    at Object.next (/root/sendexplorer/lib/explorer.js:846:13)
    at /root/sendexplorer/lib/explorer.js:1097:14
    at Object.next (/root/sendexplorer/lib/explorer.js:846:13)
    at /root/sendexplorer/lib/explorer.js:1097:14
    at Object.next (/root/sendexplorer/lib/explorer.js:846:13)
    at Object.syncLoop (/root/sendexplorer/lib/explorer.js:871:10)

Node.js v20.5.1
root@shawnvpslenexa241:~/sendexplorer# 
```

**Comment by grigzy28** [comment]
Thanks joeuhren.  It's working on syncing once again.  I hadn't ran the old way in a long time.  Will try to remember to actually read the error and not just overlook the real error in the future.

**Comment by joeuhren** [comment]
> Thanks joeuhren. It's working on syncing once again. I hadn't ran the old way in a long time. Will try to remember to actually read the error and not just overlook the real error in the future.

No worries! I would love to fix this at some point in the future, but it would take a lot of effort to move everything around which would be somewhat complicated and it already works great as long as you increase the stack size. Perhaps the better option would be to set the stack size to a higher value by default and/or allow changing the value via the config and detect the error a bit better might suffice for the short-term future. At least there is a workaround for now.

**Comment by joeuhren** [comment]
Just a note that as of today the "RangeError: Maximum call stack size exceeded" error is now being handled directly by the sync script and it should no longer be necessary to manually add the `--stack-size=[SIZE]` argument to the block sync cmd. Commit: https://github.com/team-exor/eiquidus/commit/0b0ef817f187584484e193ab115f6bdd7ed7ea4e

Now when the error occurs, the sync is smart enough to capture the error and automatically restart itself with a larger stack size and continue from where it left off. This new "elastic stack size" feature will help keep memory usage lower by not needing to permanently increase the stack size memory every time the sync script is run.

I believe I caught all the places that could trigger the error, but please create a new github issue to let me know if you are still experiencing this error with the new update in place.

As always, you can run the `npm run update-explorer` cmd to merge the latest explorer changes to take advantage of this and other updates and fixes.
