### ISSUE TITLE
Node won't startup

### ISSUE THREAD

**Issue by lurchinms** [team-exor/eiquidus#50]
kriptokyng@kriptokyng:~/explorer$ npm start
Initializing database.. Please wait..
Database initialization complete
Starting cluster with pid: 364711
That it no port number are anything.

**Comment by joeuhren** [comment]
The webserver port number is configured in the settings.json file using the webserver > port option. It defaults to port 3001:
![image](https://github.com/user-attachments/assets/e47e5162-7f3c-40bb-a2eb-a15244a213be)

Assuming you are running on the default port and the ip address of your server is 123.123.123.123 you can access the website by browsing to http://123.123.123.123:3001

**Comment by lurchinms** [comment]
ISSUE FIXED
