### ISSUE TITLE
npm sync block issue

### ISSUE THREAD

**Issue by gamgsp** [team-exor/eiquidus#52]
Hi whenever i run npm run sync block i get this error

npm run sync-blocks
Script launched with pid: 8639
Syncing blocks.. Please wait..
/home/ubuntu/explorer/lib/explorer.js:1088
      var i = loop.iteration();
                   ^

RangeError: Maximum call stack size exceeded
    at /home/ubuntu/explorer/lib/explorer.js:1088:20
    at Object.next (/home/ubuntu/explorer/lib/explorer.js:845:13)
    at /home/ubuntu/explorer/lib/explorer.js:1096:14
    at Object.next (/home/ubuntu/explorer/lib/explorer.js:845:13)
    at /home/ubuntu/explorer/lib/explorer.js:1096:14
    at Object.next (/home/ubuntu/explorer/lib/explorer.js:845:13)
    at /home/ubuntu/explorer/lib/explorer.js:1096:14
    at Object.next (/home/ubuntu/explorer/lib/explorer.js:845:13)
    at /home/ubuntu/explorer/lib/explorer.js:1096:14
    at Object.next (/home/ubuntu/explorer/lib/explorer.js:845:13)
    at /home/ubuntu/explorer/lib/explorer.js:1096:14
    at Object.next (/home/ubuntu/explorer/lib/explorer.js:845:13)
    at /home/ubuntu/explorer/lib/explorer.js:1096:14
    at Object.next (/home/ubuntu/explorer/lib/explorer.js:845:13)
    at /home/ubuntu/explorer/lib/explorer.js:1096:14
    at Object.next (/home/ubuntu/explorer/lib/explorer.js:845:13)

Node.js v22.12.0

**Comment by joeuhren** [comment]
This issue is at the top of the "Known Issues" list in the README and has been present pretty much since day 1 of the original iquidus explorer. Basically, you need to increase the amount of memory available to the sync process:
![image](https://github.com/user-attachments/assets/e3072570-e097-4822-931a-d6e2e0768004)

**Comment by gamgsp** [comment]
its fixed

**Comment by joeuhren** [comment]
Just a note that as of today the "RangeError: Maximum call stack size exceeded" error is now being handled directly by the sync script and it should no longer be necessary to manually add the `--stack-size=[SIZE]` argument to the block sync cmd. Commit: https://github.com/team-exor/eiquidus/commit/0b0ef817f187584484e193ab115f6bdd7ed7ea4e

Now when the error occurs, the sync is smart enough to capture the error and automatically restart itself with a larger stack size and continue from where it left off. This new "elastic stack size" feature will help keep memory usage lower by not needing to permanently increase the stack size memory every time the sync script is run.

I believe I caught all the places that could trigger the error, but please create a new github issue to let me know if you are still experiencing this error with the new update in place.

As always, you can run the `npm run update-explorer` cmd to merge the latest explorer changes to take advantage of this and other updates and fixes.
