### ISSUE TITLE
Masternode Count not populating

### ISSUE THREAD

**Issue by gamgsp** [team-exor/eiquidus#53]
Hi on my explorers masternodes count are not poplatting. i saw some errors sharing here please help
https://explorer.gspcoin.us/
https://explorer.globalsocialpost.com/

when i  got to https://explorer.gspcoin.us/api/getmasternodecount i get this error
Error: Check your console

An in the console of npm start i see this
Error: Method not found
    at /home/ubuntu/explorer/lib/jsonrpc.js:144:19
    at Array.forEach (<anonymous>)
    at IncomingMessage.<anonymous> (/home/ubuntu/explorer/lib/jsonrpc.js:141:15)
    at IncomingMessage.emit (node:events:536:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:90:21) {
  code: -32601

**Comment by joeuhren** [comment]
There are a number of cmds that the explorer uses to pull data from the wallet daemon, and many coins use slightly different versions of those cmds so you need to configure the explorer to use the cmds that are specific for your coin. Take a look in the "api_cmds" section of the settings.json file to review the cmds used by the explorer, and make sure that you update each cmd to match what your wallet expects. For example, the default cmd the explorer uses to get the count of masernodes is `getmasternodecount`. If you type `getmasternodecount` into you wallet daemon, does it show output like this:

```
{
  "total": 105,
  "stable": 105,
  "obfcompat": 105,
  "enabled": 105,
  "inqueue": 97,
  "ipv4": 9,
  "ipv6": 96,
  "onion": 0
}
```

If not, you need to find the equivalent cmd for your coin and update the settings.json appropriately. 

![image](https://github.com/user-attachments/assets/c44658cf-0e3b-41ba-a45e-d76779d13249)

**Comment by gamgsp** [comment]
okay i got it fixed the issue thanks for the help..
