### ISSUE TITLE
enable ssl without reverse proxy or lets encrypt

### ISSUE THREAD

**Issue by gdiscord** [team-exor/eiquidus#8]
have my own ssl certificate to use (not from lets encrypt), uploaded the files and updated settings.json as below, then restarted the explorer, but only http requests are served. https requests return "Server timeout" error.

  "webserver": {
    "port": 80,
    "tls": {      
      "enabled": true,
      "port": 443,
      "cert_file": "/etc/explorer_node/mydomain.com/mydomain.com.crt",      
      "chain_file": "/etc/explorer_node/mydomain.com/mydomain.com_chain.crt",      
      "key_file": "/etc/explorer_node/mydomain.com/mydomain.com.key"
    }

Must Nginx and letsencrypt be used in order for ssl to work?

**Comment by joeuhren** [comment]
I've not tested with any other ssl setup than what is mentioned in the README, but I don't see why it wouldn't work with another certificate. My guess is it's a permission issue and the explorer does not have access to `/etc/explorer_node/mydomain.com`. You can either try running the explorer as root with `sudo npm start` or else grant access to that directory with something like `sudo chmod -R 755 /etc/explorer_node/mydomain.com/` and restart the explorer.

I hope that helps.

**Comment by gdiscord** [comment]
Yes, already changed the permissions. My suspicion is that it's a code issue, perhaps some middleware missing from app.js?
